import type { Product, IntentionCard, StoreEvent } from '@/types';

// ─── Intention cards ────────────────────────────────────────────
export const intentionCards: IntentionCard[] = [
  {
    id: 'protection',
    label: 'Protection',
    description: 'Shield & ground your energy field',
    symbol: '⬡',
    gradient: 'from-[#1E1B4B] to-[#12102B]',
    accentColor: '#B99EE8',
    href: '/shop?intention=protection',
  },
  {
    id: 'love',
    label: 'Love',
    description: 'Open the heart. Welcome in',
    symbol: '◇',
    gradient: 'from-[#3B1A2E] to-[#12102B]',
    accentColor: '#C97BA8',
    href: '/shop?intention=love',
  },
  {
    id: 'abundance',
    label: 'Abundance',
    description: 'Align with flow. Invite prosperity',
    symbol: '✦',
    gradient: 'from-[#1A1800] to-[#12102B]',
    accentColor: '#C9A84C',
    href: '/shop?intention=abundance',
  },
  {
    id: 'clarity',
    label: 'Clarity',
    description: 'Still the mind. See the path',
    symbol: '△',
    gradient: 'from-[#0A1E2E] to-[#12102B]',
    accentColor: '#7BBAD4',
    href: '/shop?intention=clarity',
  },
  {
    id: 'healing',
    label: 'Healing',
    description: 'Tend the body. Restore the spirit',
    symbol: '✿',
    gradient: 'from-[#0A1E14] to-[#12102B]',
    accentColor: '#6DB48A',
    href: '/shop?intention=healing',
  },
  {
    id: 'grounding',
    label: 'Grounding',
    description: 'Root down. Return to earth',
    symbol: '▽',
    gradient: 'from-[#1A0F08] to-[#12102B]',
    accentColor: '#A0785A',
    href: '/shop?intention=grounding',
  },
  {
    id: 'psychic',
    label: 'Psychic',
    description: 'Sharpen the second sight',
    symbol: '☽',
    gradient: 'from-[#1E1B4B] to-[#2D1860]',
    accentColor: '#D4A8F0',
    href: '/shop?intention=psychic',
  },
  {
    id: 'shadow-work',
    label: 'Shadow work',
    description: 'Face what waits in the dark',
    symbol: '◯',
    gradient: 'from-[#0A0A14] to-[#1E1B4B]',
    accentColor: '#8B8BA8',
    href: '/shop?intention=shadow-work',
  },
];

// ─── Featured products ──────────────────────────────────────────
export const featuredProducts: Product[] = [
  {
    id: 'p1',
    slug: 'black-tourmaline-sphere',
    name: 'Black tourmaline sphere',
    price: 38,
    image: 'https://images.unsplash.com/photo-1602524816895-09edd6dcc21b?w=600&q=80',
    category: 'crystals',
    intention: ['protection', 'grounding'],
    chakra: ['root'],
    energyTags: ['Protection', 'Grounding', 'Boundary-setting'],
    isNew: false,
    isBestseller: true,
    isStaffPick: true,
    shortDescription: 'Ethically sourced guardian stone. Seals the aura, transforms anxiety into calm. Charged under the dark moon.',
  },
  {
    id: 'p2',
    slug: 'amethyst-cluster-lg',
    name: 'Amethyst cluster — cathedral grade',
    price: 74,
    compareAtPrice: 89,
    image: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=600&q=80',
    category: 'crystals',
    intention: ['clarity', 'psychic', 'healing'],
    chakra: ['third-eye', 'crown'],
    energyTags: ['Clarity', 'Psychic', 'Calm'],
    isNew: false,
    isBestseller: true,
    shortDescription: 'Deep Uruguayan amethyst. Each cluster is a natural cathedral of still energy. No two alike.',
  },
  {
    id: 'p3',
    slug: 'moon-ritual-candle-set',
    name: 'Moon ritual candle set',
    price: 28,
    image: 'https://images.unsplash.com/photo-1602524817141-bc89a4da6b2c?w=600&q=80',
    category: 'candles',
    intention: ['clarity', 'psychic', 'love'],
    energyTags: ['Lunar', 'Ritual', 'Handpoured'],
    isNew: true,
    shortDescription: 'Set of four — new, waxing, full, waning. Hand-poured soy wax with moon-aligned botanicals and essential oils.',
  },
  {
    id: 'p4',
    slug: 'wild-herb-apothecary-bundle',
    name: 'Protection herb bundle',
    price: 22,
    image: 'https://images.unsplash.com/photo-1599577180758-1da3a0c2038e?w=600&q=80',
    category: 'herbs-oils',
    intention: ['protection', 'healing'],
    energyTags: ['Wildcrafted', 'Sustainably harvested', 'Organic'],
    isNew: true,
    isLowStock: true,
    stockCount: 4,
    shortDescription: 'Rosemary, black sage, and mugwort. Sustainably wildcrafted. Tied with black cotton cord. Sourced from small farms.',
  },
  {
    id: 'p5',
    slug: 'the-wild-unknown-tarot',
    name: 'The Wild Unknown tarot',
    price: 35,
    image: 'https://images.unsplash.com/photo-1551269901-5c5e506f476c?w=600&q=80',
    category: 'tarot-oracle',
    intention: ['clarity', 'shadow-work', 'psychic'],
    energyTags: ['Tarot', 'Illustrated', 'Beginner-friendly'],
    isBestseller: true,
    shortDescription: 'Kim Krans\'s iconic nature-based deck. Gilded edges. Linen box. A perennial first deck and forever deck.',
  },
  {
    id: 'p6',
    slug: 'selenite-charging-bowl',
    name: 'Selenite charging bowl',
    price: 31,
    image: 'https://images.unsplash.com/photo-1620315808304-66597517dc08?w=600&q=80',
    category: 'altar-tools',
    intention: ['clarity', 'healing', 'psychic'],
    chakra: ['crown'],
    energyTags: ['Selenite', 'Charging', 'Cleansing'],
    isNew: false,
    isStaffPick: true,
    shortDescription: 'Hand-carved Moroccan selenite. Continuously cleanses what rests inside it. Holds crystals, rings, intentions.',
  },
  {
    id: 'p7',
    slug: 'rose-quartz-palm-stone',
    name: 'Rose quartz palm stone',
    price: 18,
    image: 'https://images.unsplash.com/photo-1596079890701-dd33e3f6f6a4?w=600&q=80',
    category: 'crystals',
    intention: ['love', 'healing'],
    chakra: ['heart'],
    energyTags: ['Love', 'Self-care', 'Gentle'],
    shortDescription: 'Polished to fit the hand perfectly. Brazilian rose quartz with deep pink saturation. A quiet companion.',
  },
  {
    id: 'p8',
    slug: 'witches-black-salt',
    name: 'Witch\'s black salt',
    price: 12,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80',
    category: 'apothecary',
    intention: ['protection', 'shadow-work'],
    energyTags: ['Protection', 'Banishing', 'Boundary'],
    isNew: false,
    isLowStock: true,
    stockCount: 7,
    shortDescription: 'Handmade with sea salt, activated charcoal, and iron filings. Sprinkle thresholds, windowsills, altars.',
  },
];

// ─── Upcoming events ────────────────────────────────────────────
export const upcomingEvents: StoreEvent[] = [
  {
    id: 'e1',
    title: 'Full moon crystal circle',
    date: 'July 13, 2025',
    time: '7:00 PM',
    description: 'Join Sandra for a guided group crystal meditation and intention-setting ritual under the Capricorn full moon.',
    price: 20,
    spotsRemaining: 6,
    href: '/events/full-moon-crystal-circle-july',
  },
  {
    id: 'e2',
    title: 'Tarot for beginners',
    date: 'July 19, 2025',
    time: '2:00 PM',
    description: 'A gentle introduction to reading tarot — symbolism, intuition, and how to develop your own practice. Decks provided.',
    price: 35,
    spotsRemaining: 3,
    href: '/events/tarot-for-beginners-july',
  },
  {
    id: 'e3',
    title: 'Book exchange drop-in day',
    date: 'July 26, 2025',
    time: '11:00 AM – 4:00 PM',
    description: 'Bring your gently loved metaphysical books, leave with store credit, and discover your next favorite read.',
    price: 'free',
    href: '/events/book-exchange-july',
  },
];
